version: '3.4'

networks:
  backend:

services:
  dbyandexeats:
    container_name: dbyandexeats-container
    image:  mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Word!5434#
    ports:
      - 1780:1433 
    networks:
      - backend
    volumes:
      - c:\mssql:/var/opt/mssql/data


  yandexeats.api:
    image: ${DOCKER_REGISTRY-}yandexeatsapi
    build:
      context: .
      dockerfile: src/YandexEatsFolder/YandexEats.API/Dockerfile
    networks:
      - backend
    ports:
      - 1456:80
  
    environment:
        - DB_HOST=dbyandexeats
        - DB_NAME=Examyandexeatsdb
        - SA_PASSWORD=Word!5434#

  yandextaxi.api:
    image: ${DOCKER_REGISTRY-}yandextaxiapi
    build:
      context: .
      dockerfile: src/YandexTaxiFolder/YandexTaxi.API/Dockerfile
    networks:
      - backend
    ports:
      - 1488:80
  
    environment:
        - DB_HOST=dbyandexeats
        - DB_NAME=Examyandextaxidb
        - SA_PASSWORD=Word!5434#



  getawayocelotexam:
    image: ${DOCKER_REGISTRY-}getawayocelotexam
    build:
      context: .
      dockerfile: src/getaway/GetawayOcelotExam/Dockerfile
    networks:
      - backend
   
  

    ports:
    - 4758:80

