version: '3.4'

networks:
  backend:

services:
  dbyandexeats:
    container_name: dbyandexeats-container
    image:  mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Word!5434#
    ports:
      - 1779:1433 
    networks:
      - backend

  yandexeats.api:
    image: ${DOCKER_REGISTRY-}yandexeatsapi
    build:
      context: .
      dockerfile: src/YandexEatsFolder/YandexEats.API/Dockerfile
    networks:
      - backend
    ports:
      - 1456:80
  
    environment:
        - DB_HOST=dbyandexeats
        - DB_NAME=yandexeatsdb
        - SA_PASSWORD=Word!5434#

  yandextaxi.api:
    image: ${DOCKER_REGISTRY-}yandextaxiapi
    build:
      context: .
      dockerfile: src/YandexTaxiFolder/YandexTaxi.API/Dockerfile




  getawayocelotexam:
    image: ${DOCKER_REGISTRY-}getawayocelotexam
    build:
      context: .
      dockerfile: src/getaway/GetawayOcelotExam/Dockerfile
    networks:
      - backend

  

    ports:
    - 4758:80

